### ISSUE TITLE
Freak lab Crash #2

### ISSUE THREAD

**Issue by ikbenmacje** [hku-ect/gazebosc#197] opened 2022-02-01 12:10 UTC
Gazebo crashed when opening the texteditor of the python actor.

I: 22-02-01 13:07:54 NOT FOUND... loading & creating text instance
Assertion failed: (self->handle), function zfile_read, file /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zfile.c, line 478.
0x7fff203ded7d: (_sigtramp+0x1d)
Gazebo version 0e6e
E: 22-02-01 13:07:54 [11191]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 13:07:54 [11191]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 13:07:54 [11191]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 13:07:54 [11191]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 13:07:54 [11191]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 13:07:54 [11191]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 13:07:54 [11191]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 13:07:54 [11191]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 13:07:54 [11191]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 13:07:54 [11191]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 13:07:54 [11191]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 13:07:54 [11191]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 13:07:54 [11191]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
Assertion failed: nbytes == sizeof (dummy) (src/signaler.cpp:395)
E: 22-02-01 13:07:54 [11191]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 13:07:54 [11191]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 13:07:54 [11191]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 13:07:54 [11191]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
0x7fff203ded7d: E: 22-02-01 13:07:54 [11191]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
(_sigtramp+0x1d)
E: 22-02-01 13:07:54 [11191]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
Gazebo version 0e6e
E: 22-02-01 13:07:54 [11191]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 13:07:54 [11191]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 13:07:54 [11191]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 13:07:54 [11191]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 13:07:54 [11191]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 13:07:54 [11191]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:601
E: 22-02-01 13:07:54 [11191]dangling 'PAIR' socket created at /Users/runner/work/gazebosc/gazebosc/ext/czmq/src/zsys.c:602
E: 22-02-01 13:07:54 [11191]dangling 'PUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:131
E: 22-02-01 13:07:54 [11191]dangling 'SUB' socket created at /Users/runner/work/gazebosc/gazebosc/ext/libsphactor/src/sphactor_actor.c:136
E: 22-02-01 13:07:54 dangling sockets: cannot terminate ZMQ safely

**Comment by sphaero** [comment] 2022-02-04 10:27
Any idea what you did that resulted in this crash? I can't reproduce it

**Comment by sphaero** [comment] 2022-02-04 10:30
A crash could be triggered when you load a python file and then remove it from disk. If you open the texteditor then it will crash. However the assert is on a different line then

**Comment by sphaero** [comment] 2022-03-25 10:39
I think this is fixed with the new working dir management

**Closed by sphaero** 2022-03-25 10:39 UTC
